POST http://localhost:8080/v1/auth/login/social
Content-Type: application/json

{
  "email": "khangdev.hcm@gmail.com",
  "uid": "khandev"
}

###
GET http://localhost:8080/v1/categories/9494972361347072
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJPcHVsZW50aWEtYWNjZXNzIiwic3ViIjoiMTIzMjQiLCJleHAiOjE3NDA2NDI4MTYsImlhdCI6MTc0MDYzOTIxNn0.Rzla3pNCvJRWgyvZ7he717cdxh9tTjlZQYpkzPLn1Pc



